version: "3"

services:
  app:
    restart: always
    build: .
    ports:
      - "6700:6700"

  {%- if cookiecutter.use_sqlmodel == 'y' %}
  postgresql:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: ...
      POSTGRES_PASSWORD: ...
      POSTGRES_DB: ...
    volumes:
      - postgresql-data:/var/lib/postgresql/data/
    ports:
      - 5888:5432
  {%- endif %}

  {%- if cookiecutter.use_mongoengine == 'y' %}
  mongo:
    restart: always
    image: bitnami/mongodb
    environment:
      MONGODB_ROOT_USER: ...
      MONGODB_ROOT_PASSWORD: ...
      MONGODB_USERNAME: ...
      MONGODB_PASSWORD: ...
      MONGODB_DATABASE: ...
    volumes:
      - mongo-data:/bitnami/mongodb
    ports:
      - 27017:27017
  {%- endif %}

  {%- if cookiecutter.use_cache == 'y' %}
  redis:
    image: redis:alpine
    restart: always
    ports:
    -   6900:6379
    volumes:
    -   redis-data:/data
  {%- endif %}

volumes:
  {% if cookiecutter.use_sqlmodel == 'y' -%}
  postgresql-data:
  {% endif -%}

  {% if cookiecutter.use_mongoengine == 'y' -%}
  mongo-data:
  {% endif -%}

  {% if cookiecutter.use_cache == 'y' -%}
  redis-data:
  {%- endif -%}
